# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "lab_02" do |lb2|

    lb2.vm.box = "hashicorp/bionic64"
    lb2.vm.network "private_network", ip: "192.168.57.14"
    lb2.vm.provider "virtualbox" do |vb|

      vb.memory = "512"
      vb.cpus = 1
    end
  end
end