# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "lab01" do |m1|
    m1.vm.box = "ubuntu/bionic64"
    m1.vm.hostname = "hiosaki"
    m1.vm.provision "shell", path: "provision.sh"
    m1.vm.provider "virtualbox" do |vb|
      vb.name = "server-linux"
      vb.memory = "256"
      vb.cpus = 1

    end
  end
end
